// <auto-generated />
using System;
using ManagerCovid19.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManagerCovid19.Migrations
{
    [DbContext(typeof(ManagerCovid19Context))]
    [Migration("20211103154017_Remove_Admin_Col")]
    partial class Remove_Admin_Col
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManagerCovid19.Models.HealthRegistration", b =>
                {
                    b.Property<int>("HealthRegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Calafrios")
                        .HasColumnType("bit");

                    b.Property<bool>("Cansaco")
                        .HasColumnType("bit");

                    b.Property<bool>("Coriza")
                        .HasColumnType("bit");

                    b.Property<bool>("Diarreia")
                        .HasColumnType("bit");

                    b.Property<bool>("DorDeCabeca")
                        .HasColumnType("bit");

                    b.Property<bool>("DorDeGarganta")
                        .HasColumnType("bit");

                    b.Property<bool>("DorNoPeito")
                        .HasColumnType("bit");

                    b.Property<bool>("Espirros")
                        .HasColumnType("bit");

                    b.Property<bool>("FaltaDeAr")
                        .HasColumnType("bit");

                    b.Property<bool>("Febre")
                        .HasColumnType("bit");

                    b.Property<bool>("HowRUFeeling")
                        .HasColumnType("bit");

                    b.Property<string>("MemberRegistrationNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PerdaDeOlfato")
                        .HasColumnType("bit");

                    b.Property<bool>("PerdaPaladar")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Tosse")
                        .HasColumnType("bit");

                    b.HasKey("HealthRegistrationID");

                    b.HasIndex("MemberRegistrationNumber");

                    b.ToTable("HealthRegistration");
                });

            modelBuilder.Entity("ManagerCovid19.Models.Member", b =>
                {
                    b.Property<string>("MemberRegistrationNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberRegistrationNumber");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("ManagerCovid19.Models.HealthRegistration", b =>
                {
                    b.HasOne("ManagerCovid19.Models.Member", "Member")
                        .WithMany("HealthRegistrations")
                        .HasForeignKey("MemberRegistrationNumber");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ManagerCovid19.Models.Member", b =>
                {
                    b.Navigation("HealthRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
